default:
  width: 600
  height: 400
  convert_urls: false
  verify_html: false
  plugins:
    - layer
    - table
    - searchreplace
    - contextmenu
    - paste
    - fullscreen
    - visualchars
    - nonbreaking
  theme_advanced_buttons1:
    - bold
    - italic
    - underline
    - strikethrough
    - formatselect
    - fontsizeselect
    - hr
    - link
    - unlink
    - code
    - fullscreen
  theme_advanced_buttons2:
    - selectall
    - cut
    - copy
    - paste
    - pastetext
    - pasteword
    - replace
    - bullist
    - numlist
    - outdent
    - indent
    - removeformat
    - charmap
    - visualaid
    - image
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: bottom
